### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by since2016-05-22** [redox-os/redox#650]
**Reproduction**: [run "lazy" script on https://doc.redox-os.org/book/getting_started/preparing_the_build.html]

**Expected behavior**: []

**Actual behavior**: [Compiling fuse v0.2.7
error: failed to run custom build command for `fuse v0.2.7`
Process didn't exit successfully: `/home/user/Downloads/redox/redox/crates/redoxfs/target/debug/build/fuse-5b87eb71951205b4/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\"`: No such file or directory (os error 2)"', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Makefile:566: recipe for target 'build/i386-unknown-redox/debug/filesystem.bin' failed
make: *** [build/i386-unknown-redox/debug/filesystem.bin] Error 101].

**Build information**: [output of `rustc -V`:multirust: no default toolchain configured, `git rev-parse HEAD`: d307aa23de0a1fe8de1e8254ce33626816ef6f84,  `uname -a`: Linux debian 4.5.0-0.bpo.2-amd64 #1 SMP Debian 4.5.3-2~bpo8+1 (2016-05-13) x86_64 GNU/Linux]

------

**Comment by DomThePorcupine** [comment]
It appears the current build is failing. Did the bootstrap not warn you of this?

**Comment by bjorn3** [comment]
Have you installed fuse?

**Comment by since2016-05-22** [comment]
Yes

**Comment by jackpot51** [comment]
What about pkg-config?

**Comment by DomThePorcupine** [comment]
@jackpot51 is pjg-config a dependencies for non osx systems? We do not have that outlined in the readme, or in setup/ubuntu.sh so I did not put it in the bootstrap and when we tested it earlier it seemed to work fine

**Comment by xliiv** [comment]
I also installed fuse and got this error.

**Comment by jawbonegroove** [comment]
i also received this error on initial make all; ran it again with backtrace=1 and exited no errors, ran in qemu just fine. running arch, all deps preinstalled.

**Comment by since2016-05-22** [comment]
`make clean`
`make all RUST_BACKTRACE=1`

```
   Compiling fuse v0.2.7
error: failed to run custom build command for `fuse v0.2.7`
Process didn't exit successfully: `/home/b/Downloads/redox/redox/crates/redoxfs/target/debug/build/fuse-5b87eb71951205b4/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\"`: No such file or directory (os error 2)"', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x555b10e0e5d4 - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x555b10e1568b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x555b10e15313 - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x555b10e03f0d - std::panicking::rust_panic_with_hook::h587239a80cad02d2
   5:     0x555b10e15921 - std::panicking::begin_panic::h77cefecf7d758cdf
   6:     0x555b10e0544a - std::panicking::begin_panic_fmt::hb3024643f3039337
   7:     0x555b10e158b1 - rust_begin_unwind
   8:     0x555b10e4b30f - core::panicking::panic_fmt::h5594591d20dedfcd
   9:     0x555b10df0559 - core::result::unwrap_failed::hc37550fe6212c12b
                        at ../src/libcore/macros.rs:29
  10:     0x555b10defb2e - _<core..result..Result<T, E>>::unwrap::h499ca4af10fdfee6
                        at ../src/libcore/result.rs:723
  11:     0x555b10dee6e8 - build_script_build::main::he5071e1b00fcfe0e
                        at /root/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.2.7/build.rs:12
  12:     0x555b10e14f58 - std::panicking::try::call::hd0906b54b9bfbb20
  13:     0x555b10e1f50b - __rust_try
  14:     0x555b10e1f4ae - __rust_maybe_catch_panic
  15:     0x555b10e1498c - std::rt::lang_start::hfe4efe1fc39e4a30
  16:     0x555b10df07e9 - main
  17:     0x7f6b3c1bdb44 - __libc_start_main
  18:     0x555b10dee358 - <unknown>
  19:                0x0 - <unknown>

Makefile:566: recipe for target 'build/i386-unknown-redox/debug/filesystem.bin' failed
make: *** [build/i386-unknown-redox/debug/filesystem.bin] Error 101

```

**Comment by xliiv** [comment]
some here:

```
cp build/i386-unknown-redox/debug/ion-shell.bin filesystem/bin/sh
mkdir -p filesystem/bin
cp libc/bin/tar filesystem/bin/tar
rm -rf build/i386-unknown-redox/debug/filesystem.bin build/i386-unknown-redox/debug/filesystem/
echo exit | cargo run --manifest-path crates/redoxfs/Cargo.toml --bin redoxfs-utility build/i386-unknown-redox/debug/filesystem.bin
   Compiling fuse v0.2.7
error: failed to run custom build command for `fuse v0.2.7`
Process didn't exit successfully: `/home/xliiv/workspace/redox/redox/crates/redoxfs/target/debug/build/fuse-5b87eb71951205b4/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\"`: No such file or directory (os error 2)"', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x56385a5605c4 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x56385a5676bb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x56385a567343 - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x56385a555efd - std::panicking::rust_panic_with_hook::hfe203e3083c2b544
   5:     0x56385a567951 - std::panicking::begin_panic::h4889569716505182
   6:     0x56385a55743a - std::panicking::begin_panic_fmt::h484cd47786497f03
   7:     0x56385a5678e1 - rust_begin_unwind
   8:     0x56385a59d33f - core::panicking::panic_fmt::h257ceb0aa351d801
   9:     0x56385a542549 - core::result::unwrap_failed::hb1ced490f1c4ca85
                        at ../src/libcore/macros.rs:29
  10:     0x56385a541b1e - _<core..result..Result<T, E>>::unwrap::hbedab81fc5e0c323
                        at ../src/libcore/result.rs:723
  11:     0x56385a5406d8 - build_script_build::main::he5071e1b00fcfe0e
                        at /home/xliiv/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.2.7/build.rs:12
  12:     0x56385a566f88 - std::panicking::try::call::hc5e1f5b484ec7f0e
  13:     0x56385a57153b - __rust_try
  14:     0x56385a5714de - __rust_maybe_catch_panic
  15:     0x56385a5669bc - std::rt::lang_start::h61f4934e780b4dfc
  16:     0x56385a5427d9 - main
  17:     0x7fb5baf1982f - __libc_start_main
  18:     0x56385a540348 - _start
  19:                0x0 - <unknown>

Makefile:566: recipe for target 'build/i386-unknown-redox/debug/filesystem.bin' failed
make: *** [build/i386-unknown-redox/debug/filesystem.bin] Error 101

```

**Comment by zaklaus** [comment]
Same:
```
   Compiling fuse v0.2.7
error: failed to run custom build command for `fuse v0.2.7`
Process didn't exit successfully: `/root/redox/crates/redoxfs/target/debug/build/fuse-5b87eb71951205b4/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\"`: No such file or directory (os error 2)"', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x7f2bad0cf844 - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x7f2bad0d693b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x7f2bad0d65bf - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x7f2bad0c505d - std::panicking::rust_panic_with_hook::h587239a80cad02d2
   5:     0x7f2bad0d6bd1 - std::panicking::begin_panic::h77cefecf7d758cdf
   6:     0x7f2bad0c659a - std::panicking::begin_panic_fmt::hb3024643f3039337
   7:     0x7f2bad0d6b61 - rust_begin_unwind
   8:     0x7f2bad10c5bf - core::panicking::panic_fmt::h5594591d20dedfcd
   9:     0x7f2bad0b15b5 - core::result::unwrap_failed::hc37550fe6212c12b
                        at ../src/libcore/macros.rs:29
  10:     0x7f2bad0b0b7e - _<core..result..Result<T, E>>::unwrap::h499ca4af10fdfee6
                        at ../src/libcore/result.rs:723
  11:     0x7f2bad0af6e8 - build_script_build::main::he5071e1b00fcfe0e
                        at /root/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.2.7/build.rs:12
  12:     0x7f2bad0d61f8 - std::panicking::try::call::hd0906b54b9bfbb20
  13:     0x7f2bad0e07bb - __rust_try
  14:     0x7f2bad0e075e - __rust_maybe_catch_panic
  15:     0x7f2bad0d5c2c - std::rt::lang_start::hfe4efe1fc39e4a30
  16:     0x7f2bad0b1849 - main
  17:     0x7f2bac4c4b44 - __libc_start_main
  18:     0x7f2bad0af358 - <unknown>
  19:                0x0 - <unknown>

Makefile:566: recipe for target 'build/i386-unknown-redox/debug/filesystem.bin' failed
make: *** [build/i386-unknown-redox/debug/filesystem.bin] Error 101

```

**Comment by IAmRasputin** [comment]
Same, running Debian Testing:

````
Compiling fuse v0.2.7
error: failed to run custom build command for `fuse v0.2.7`
Process didn't exit successfully: `/home/rmg/Documents/Code/GitHub/redox/crates/redoxfs/target/debug/build/fuse-5b87eb71951205b4/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\"` did not exit successfully: exit code: 1\n--- stdout\nPackage fuse was not found in the pkg-config search path.\nPerhaps you should add the directory containing `fuse.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'fuse\' found\n"', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x55c4202f4824 - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x55c4202fb95b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x55c4202fb5df - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x55c4202ea03e - std::panicking::rust_panic_with_hook::h587239a80cad02d2
   5:     0x55c4202fbbf1 - std::panicking::begin_panic::h77cefecf7d758cdf
   6:     0x55c4202eb57a - std::panicking::begin_panic_fmt::hb3024643f3039337
   7:     0x55c4202fbb81 - rust_begin_unwind
   8:     0x55c4203315df - core::panicking::panic_fmt::h5594591d20dedfcd
   9:     0x55c4202d6529 - core::result::unwrap_failed::hc37550fe6212c12b
                        at ../src/libcore/macros.rs:29
  10:     0x55c4202d5aee - _<core..result..Result<T, E>>::unwrap::h499ca4af10fdfee6
                        at ../src/libcore/result.rs:723
  11:     0x55c4202d4658 - build_script_build::main::he5071e1b00fcfe0e
                        at /home/rmg/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.2.7/build.rs:12
  12:     0x55c4202fb218 - std::panicking::try::call::hd0906b54b9bfbb20
  13:     0x55c4203057db - __rust_try
  14:     0x55c42030577e - __rust_maybe_catch_panic
  15:     0x55c4202fac4c - std::rt::lang_start::hfe4efe1fc39e4a30
  16:     0x55c4202d67b9 - main
  17:     0x7f217f5d460f - __libc_start_main
  18:     0x55c4202d42c8 - _start
  19:                0x0 - <unknown>

Makefile:584: recipe for target 'build/i386-unknown-redox/debug/filesystem.bin' failed
make: *** [build/i386-unknown-redox/debug/filesystem.bin] Error 101
```

This is after running `make clean`.  pkg-config and fuse are installed.

**Comment by jackpot51** [comment]
Do you have libfuse-dev installed?

**Comment by xliiv** [comment]
I have:
```
xliiv@alef ~> aptitude show libfuse-dev
Package: libfuse-dev                     
State: installed
Automatically installed: no
Version: 2.9.4-1ubuntu3
Priority: optional
Section: libdevel
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 598 k
Depends: libfuse2 (= 2.9.4-1ubuntu3), libselinux-dev
Suggests: fuse
Conflicts: libfuse-dev:i386
Description: Filesystem in Userspace (development)
 Filesystem in Userspace (FUSE) is a simple interface for userspace programs to export a virtual filesystem to the Linux kernel. It
 also aims to provide a secure method for non privileged users to create and mount their own filesystem implementations. 
 
 This package contains the development files.
Homepage: http://fuse.sourceforge.net/
```
and still got error.

**Comment by since2016-05-22** [comment]
```
dpkg -s libfuse-dev
Package: libfuse-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 590
Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>
Architecture: amd64
Source: fuse
Version: 2.9.3-15+deb8u2
Depends: libfuse2 (= 2.9.3-15+deb8u2), libselinux-dev
Suggests: fuse
Description: Filesystem in Userspace (development)
 Filesystem in Userspace (FUSE) is a simple interface for userspace programs to
 export a virtual filesystem to the Linux kernel. It also aims to provide a
 secure method for non privileged users to create and mount their own filesystem
 implementations.
 .
 This package contains the development files.
Homepage: http://fuse.sourceforge.net/

```

**Comment by since2016-05-22** [comment]
**Solved**: I've installed `pkg-config` and added the directory containing `fuse.pc` to the `PKG_CONFIG_PATH` environment variable.

**Comment by xliiv** [comment]
:+1: It also works for me.
Thanks :)

**Comment by since2016-05-22** [comment]
You are welcome :-)
