### ISSUE TITLE
Make all command exits (fuse 0.2.8 does not compile) 

### ISSUE THREAD

**Issue by mrLSD** [redox-os/redox#858]
**Reproduction**: run Vagrant + VirtualBox (virtualbox-5.1/now 5.1.14-112924~Ubuntu~xenial) with clear Ubuntu 16.04, running on Ununtu 16.04. All packages upgraded. Run make all command in the redox directory after downloading everything with bootstrap.sh

**Expected behavior**: the compilation finishes without errors.

**Actual behavior**: the following error is printed on the screen:
```

$ make clean
$ make all
   Compiling fuse v0.2.8
error: failed to run custom build command for `fuse v0.2.8`
process didn't exit successfully: `/home/ubuntu/rs/redox/target/release/build/fuse-8cf59128d87b5825/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\"", cause: Error { repr: Os { code: 20, message: "Not a directory" } } }', /checkout/src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.

mk/filesystem.mk:2: recipe for target 'build/filesystem.bin' failed
make: *** [build/filesystem.bin] Error 101

```
**Build information**: 
```
$ rustc --version
rustc 1.17.0-nightly (08230775a 2017-02-24

$ lsb_release -d
Description:	Ubuntu 16.04.2 LTS

$ uname -a
Linux virtuos 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ qemu-i386 -version
qemu-i386 version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.9), Copyright (c) 2003-2008 Fabrice Bellard

$ qemu-x86_64 -version
qemu-x86_64 version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.9), Copyright (c) 2003-2008 Fabrice Bellard


$ dpkg -s  libfuse-dev
Package: libfuse-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 585
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: fuse
Version: 2.9.4-1ubuntu3.1
Depends: libfuse2 (= 2.9.4-1ubuntu3.1), libselinux-dev
Suggests: fuse

$ dpkg -s fuse
Package: fuse
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 104
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.9.4-1ubuntu3.1
Depends: libc6 (>= 2.14), libfuse2 (= 2.9.4-1ubuntu3.1), adduser, mount (>= 2.19.1), sed (>= 4)
Conffiles:
 /etc/fuse.conf 298587592c8444196833f317def414f2

$ RUST_BACKTRACE=1 make all
   Compiling fuse v0.2.8
error: failed to run custom build command for `fuse v0.2.8`
process didn't exit successfully: `/home/ubuntu/rs/redox/target/release/build/fuse-8cf59128d87b5825/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\"", cause: Error { repr: Os { code: 20, message: "Not a directory" } } }', /checkout/src/libcore/result.rs:860
stack backtrace:
   1:     0x55e11a489c79 - std::sys::imp::backtrace::tracing::imp::write::hbb14611794d3841b
                        at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55e11a48ec6e - std::panicking::default_hook::{{closure}}::h6ed906c7818ac88c
                        at /checkout/src/libstd/panicking.rs:351
   3:     0x55e11a48e874 - std::panicking::default_hook::h23eeafbf7c1c05c3
                        at /checkout/src/libstd/panicking.rs:367
   4:     0x55e11a48f00b - std::panicking::rust_panic_with_hook::hd0067971b6d1240e
                        at /checkout/src/libstd/panicking.rs:545
   5:     0x55e11a48ee94 - std::panicking::begin_panic::h1fd1f10a3de8f902
                        at /checkout/src/libstd/panicking.rs:507
   6:     0x55e11a48ee09 - std::panicking::begin_panic_fmt::haa043917b5d6f21b
                        at /checkout/src/libstd/panicking.rs:491
   7:     0x55e11a48ed97 - rust_begin_unwind
                        at /checkout/src/libstd/panicking.rs:467
   8:     0x55e11a4b4efd - core::panicking::panic_fmt::he9c7f335d160b59d
                        at /checkout/src/libcore/panicking.rs:69
   9:     0x55e11a47ba93 - core::result::unwrap_failed::h55da8396d8dca29e
  10:     0x55e11a47bf40 - build_script_build::main::h0d3215d7cc0227df
  11:     0x55e11a49796a - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  12:     0x55e11a48f7b6 - std::rt::lang_start::hb7fc7ec87b663023
                        at /checkout/src/libstd/panicking.rs:429
                        at /checkout/src/libstd/panic.rs:361
                        at /checkout/src/libstd/rt.rs:57
  13:     0x7f3fc5f6782f - __libc_start_main
  14:     0x55e11a47b8c8 - _start
  15:                0x0 - <unknown>

mk/filesystem.mk:2: recipe for target 'build/filesystem.bin' failed

```

What is wrong?

**Comment by bjorn3** [comment]
do you have pkg-config installed?

**Comment by mrLSD** [comment]
That helped. Maybe it should added to bootstrap dependencies?

**Comment by komawoyo** [comment]
yes, I also ran into the problem of the missing `pkg-config`
